name: build_my_v8

on: 
  workflow_dispatch:
    inputs:
      tag_date:
        description: 'tag date'
        type: string
        default: ""
        required: false
      v8_revision:
        description: 'V8 TAG(Branch) to build'
        type: choice
        options:
        - "9.4.146.24"
        - "10.6.194"
        - "11.8.172"
        default: '9.4.146.24'
        required: true
      wrap_new:
        description: 'wrap new/delete'
        type: choice
        options:
        - "with_new_wrap"
        - ""
        default: ""
        required: false

      build_windows:
        description: 'Build for Windows platform'
        type: boolean
        default: true
        required: false

  

jobs:
  build_linux:
    if: github.event.inputs.build_linux == 'true'
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        npm i
        bash ./mylinux.sh ${{github.event.inputs.v8_revision}} ${{github.event.inputs.wrap_new}}
        mv ~/v8/v8/output/v8 ~/v8/v8/output/v8_${{github.event.inputs.v8_revision}}
    - uses: actions/upload-artifact@v4
      with:
        name: v8_bin_linux
        path: ~/v8/v8/output/**/*
        
        
  
